jobs:
  docs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.SDQ_DEV_DEPLOY_TOKEN }}
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        path: wiki
        repository: ${{ github.repository }}.wiki
        token: ${{ secrets.SDQ_DEV_DEPLOY_TOKEN }}
    - continue-on-error: true
      name: Remove contents in Wiki
      run: ls -A1 | grep -v '.git' | xargs rm -r
      working-directory: wiki
    - continue-on-error: true
      name: Copy Wiki from Docs folder
      run: cp -r ./docs/. ./wiki
    - continue-on-error: true
      name: "Deploy \U0001F680"
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        repository: wiki
name: Documentation
on:
  repository_dispatch:
    types: trigger-ga___docs.yml
