jobs:
  sonarcloud:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: SonarCloud
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_REPORT_VIEWER }}
      name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: report-viewer
name: SonarCloud Scan (ReportViewer)
on:
  repository_dispatch:
    types: trigger-ga___report-viewer-sonarcloud.yml
