jobs:
  build-and-deploy:
    needs: run-example
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: "Checkout \U0001F6CE\uFE0F"
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - continue-on-error: true
      name: Set version of Report Viewer
      run: 'VERSION=$(grep "<revision>" pom.xml | grep -oPm1 "(?<=<revision>)[^-|<]+")

        MAJOR=$(echo $VERSION | cut -d ''.'' -f 1)

        MINOR=$(echo $VERSION | cut -d ''.'' -f 2)

        PATCH=$(echo $VERSION | cut -d ''.'' -f 3)

        json=$(cat report-viewer/src/version.json)

        json=$(echo "$json" | jq --arg MAJOR "$MAJOR" --arg MINOR "$MINOR" --arg PATCH
        "$PATCH" ''.report_viewer_version |= { "major": $MAJOR | tonumber, "minor":
        $MINOR | tonumber, "patch": $PATCH | tonumber }'')

        echo "$json" >  report-viewer/src/version.json

        echo "Version of Report Viewer:"

        cat report-viewer/src/version.json

        '
      shell: bash
    - continue-on-error: true
      name: Download Results
      uses: actions/download-artifact@v4
      with:
        name: Result
        path: report-viewer/public
    - continue-on-error: true
      name: "Install and Build \U0001F527"
      run: 'npm install

        npm run build-demo

        '
      working-directory: report-viewer
    - continue-on-error: true
      name: "Deploy \U0001F680"
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        branch: gh-pages
        clean: true
        folder: report-viewer/dist
        repository-name: JPlag/Demo
        single-commit: true
        token: ${{ secrets.SDQ_DEV_DEPLOY_TOKEN }}
  build-jar:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: "Checkout \U0001F6CE\uFE0F"
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Build Assembly
      run: mvn clean package assembly:single
    - continue-on-error: true
      name: Upload Assembly
      uses: actions/upload-artifact@v4
      with:
        name: JPlag
        path: cli/target/jplag-*-jar-with-dependencies.jar
  run-example:
    needs: build-jar
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: "Checkout \U0001F6CE\uFE0F"
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Get JAR
      uses: actions/download-artifact@v4
      with:
        name: JPlag
    - continue-on-error: true
      name: Copy and unzip submissions
      run: unzip ./.github/workflows/files/progpedia.zip
    - continue-on-error: true
      name: Rename jar
      run: mv *.jar ./jplag.jar
    - continue-on-error: true
      name: Run JPlag
      run: java -jar jplag.jar ACCEPTED -bc base -r example
    - continue-on-error: true
      name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: Result
        path: example.zip
name: Report Viewer Demo Deployment
on:
  repository_dispatch:
    types: trigger-ga___report-viewer-demo.yml
