jobs:
  check:
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    needs: pre_job
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: "Checkout \U0001F6CE\uFE0F"
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - continue-on-error: true
      name: "Install and Check \U0001F3A8"
      run: 'npm install

        npx prettier --check src/**/*.ts

        npx prettier --check src/**/*.vue

        '
      working-directory: report-viewer
  pre_job:
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: skip_check
      uses: fkirc/skip-duplicate-actions@master
      with:
        concurrent_skipping: same_content_newer
        skip_after_successful_duplicate: 'true'
name: Report Viewer Prettier Check Workflow
on:
  repository_dispatch:
    types: trigger-ga___report-viewer-prettier.yml
