jobs:
  get-info:
    if: ${{ github.actor != 'dependabot[bot]' && github.event.workflow_run.conclusion
      == 'success' }}
    name: Get information about the source run
    outputs:
      mergeCommitSha: ${{ steps.source-run-info.outputs.mergeCommitSha }}
      pullRequestLabels: ${{ steps.source-run-info.outputs.pullRequestLabels }}
      pullRequestNumber: ${{ steps.source-run-info.outputs.pullRequestNumber }}
      sourceEvent: ${{ steps.source-run-info.outputs.sourceEvent }}
      sourceHeadBranch: ${{ steps.source-run-info.outputs.sourceHeadBranch }}
      sourceHeadRepo: ${{ steps.source-run-info.outputs.sourceHeadRepo }}
      sourceHeadSha: ${{ steps.source-run-info.outputs.sourceHeadSha }}
      targetBranch: ${{ steps.source-run-info.outputs.targetBranch }}
      targetCommitSha: ${{ steps.source-run-info.outputs.targetCommitSha }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: source-run-info
      name: Get information about the origin 'CI' run
      uses: potiuk/get-workflow-origin@v1_3
      with:
        sourceRunId: ${{ github.event.workflow_run.id }}
        token: ${{ secrets.GITHUB_TOKEN }}
  sonar:
    if: ${{ needs.get-info.outputs.sourceEvent == 'pull_request' && github.actor !=
      'dependabot[bot]' && github.event.workflow_run.conclusion == 'success' }}
    name: SonarCloud Scan
    needs: get-info
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.workflow_run.head_branch }}
        repository: ${{ github.event.workflow_run.head_repository.full_name }}
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Build and analyze (PR)
      run: 'mvn  -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }}  -Dsonar.pullrequest.key=${{
        needs.get-info.outputs.pullRequestNumber }}  -Dsonar.pullrequest.branch=${{
        needs.get-info.outputs.sourceHeadBranch }}  -Dsonar.pullrequest.base=${{ needs.get-info.outputs.pullRequestNumber
        }}  -U -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

        '
name: SonarCloud Scan (PRs triggered by maven.yml)
on:
  repository_dispatch:
    types: trigger-ga___sonarcloud-pr.yml
